// src/data.jsx
// Mock data — realistische Nederlandse leads voor Schoon Straatje
// Geen library-imports, alles globals/window-attached

const FASES = {
  info_verzamelen:        { label: 'Info verzamelen',   tone: 'blue'  },
  offerte_besproken:      { label: 'Offerte besproken', tone: 'amber' },
  onderhandelen:          { label: 'Onderhandelen',     tone: 'amber' },
  datum_kiezen:           { label: 'Datum kiezen',      tone: 'blue'  },
  afspraak_bevestigd:     { label: 'Afspraak vast',     tone: 'green' },
  afspraak_geannuleerd:   { label: 'Geannuleerd',       tone: 'red'   },
};

const STATUS = {
  nieuw:              { label: 'Nieuw',              tone: 'blue'  },
  in_gesprek:         { label: 'In gesprek',         tone: 'blue'  },
  wacht_bevestiging:  { label: 'Wacht op bevestig.', tone: 'amber' },
  info_compleet:      { label: 'Klaar voor offerte', tone: 'amber' },
  offerte_verstuurd:  { label: 'Offerte verstuurd',  tone: 'amber' },
  goedgekeurd:        { label: 'Goedgekeurd',        tone: 'green' },
  afgewezen:          { label: 'Afgewezen',          tone: 'red'   },
  handoff:            { label: 'Handover',           tone: 'red'   },
};

const DIENST_LABELS = {
  invegen:                          'Voegen invegen',
  preventieve_onkruid:              'Preventieve onkruidbehandeling',
  preventieve_onkruidbeheersing:    'Preventieve onkruidbeheersing',
  beschermlaag:                     'Nieuwe beschermlaag',
  onderhoud:                        'Onderhoudsplan',
  plan_4_weken:                     'Onderhoud — elke 4 weken',
  plan_8_weken:                     'Onderhoud — elke 8 weken',
  plan_12_weken:                    'Onderhoud — elke 12 weken',
  plan_16_weken:                    'Onderhoud — elke 16 weken',
  reinigen:                         'Reiniging straatwerk',
};

// 5 pipeline-kolommen (gesprek-fase-georiënteerd)
const PIPELINE_STAGES = [
  { key: 'info',     label: 'In gesprek',     match: l => ['nieuw','in_gesprek'].includes(l.status) },
  { key: 'review',   label: 'Offerte review', match: l => l.status === 'info_compleet' || l.status === 'wacht_bevestiging' },
  { key: 'verstuurd',label: 'Offerte uit',    match: l => l.status === 'offerte_verstuurd' },
  { key: 'gepland',  label: 'Ingepland',      match: l => l.status === 'goedgekeurd' && l.afspraak_datum },
  { key: 'klaar',    label: 'Afgerond',       match: l => l.dashboard_status === 'afgehandeld' },
];

const LEADS = [
  {
    id: 'L-2087',
    naam: 'Jeroen de Vries',
    bedrijf: null,
    telefoon: '06 - 24 96 52 70',
    email: 'jeroen.devries@gmail.com',
    adres: 'Lindenlaan 14, 2611 GH Delft',
    afstand_km: 18,
    hoofd: 'oprit_terras_terrein',
    sub: ['invegen', 'beschermlaag'],
    m2: 145,
    planten: 'ja',
    planten_afschermen: 'ja',
    groene_aanslag: 'ja',
    korstmos: 'nee',
    voegzand_type: 'onkruidwerend',
    zand_kleur: 'antraciet',
    fotos: 4,
    status: 'in_gesprek',
    fase: 'info_verzamelen',
    dashboard_status: 'open',
    totaal_prijs: null,
    binnengekomen: '8 min geleden',
    laatste_bericht: 'Hoi! Ja, ongeveer 145m² inderdaad. Foto\'s heb ik net gestuurd.',
    laatste_richting: 'inkomend',
    wacht_op_klant: false,
    bot_volgende_actie: 'Vraagt om bevestiging m²',
    tag: ['Particulier'],
    binnen_ts: Date.now() - 8 * 60 * 1000,
    bron: 'formulier',
  },
  {
    id: 'L-2086',
    naam: 'Bouwbedrijf Korstmos B.V.',
    bedrijf: 'Korstmos B.V.',
    telefoon: '06 - 12 34 56 78',
    email: 'planning@korstmos.nl',
    adres: 'Industrieweg 88, 4521 CB Biervliet',
    afstand_km: 4,
    hoofd: 'onkruidbeheersing_zakelijk',
    sub: ['plan_8_weken'],
    m2: 2200,
    planten: 'nee',
    groene_aanslag: 'ja',
    korstmos: 'ja',
    voegzand_type: null,
    fotos: 8,
    status: 'offerte_verstuurd',
    fase: 'offerte_besproken',
    dashboard_status: 'opgevolgd',
    totaal_prijs: 4180,
    binnengekomen: '2 uur geleden',
    laatste_bericht: 'Helder. We kijken er deze week naar en komen erop terug.',
    laatste_richting: 'inkomend',
    wacht_op_klant: false,
    bot_volgende_actie: 'Wacht op reactie',
    tag: ['Zakelijk', 'Repeat'],
    binnen_ts: Date.now() - 2 * 3600 * 1000,
    offerte_verstuurd_op: 'gister 16:42',
    bron: 'whatsapp',
  },
  {
    id: 'L-2085',
    naam: 'Marieke van der Heijden',
    bedrijf: null,
    telefoon: '06 - 88 91 22 30',
    email: 'm.vdheijden@outlook.com',
    adres: 'Zandweg 7, 3034 EM Rotterdam',
    afstand_km: 24,
    hoofd: 'oprit_terras_terrein',
    sub: ['invegen'],
    m2: 62,
    planten: 'nee',
    groene_aanslag: 'nee',
    korstmos: 'nee',
    voegzand_type: 'normaal',
    zand_kleur: 'naturel',
    fotos: 3,
    status: 'goedgekeurd',
    fase: 'afspraak_bevestigd',
    dashboard_status: 'open',
    totaal_prijs: 612,
    binnengekomen: '3 dagen geleden',
    laatste_bericht: 'Top, tot dinsdag! 👍',
    laatste_richting: 'inkomend',
    wacht_op_klant: false,
    bot_volgende_actie: 'Stuurt herinnering 24u voor afspraak',
    tag: ['Particulier'],
    binnen_ts: Date.now() - 3 * 86400 * 1000,
    afspraak_datum: '2026-05-19',
    afspraak_starttijd: '09:00',
    bron: 'formulier',
  },
  {
    id: 'L-2084',
    naam: 'Familie Bakker',
    bedrijf: null,
    telefoon: '06 - 47 33 12 90',
    email: 'r.bakker@kpnmail.nl',
    adres: 'Eikenlaan 22, 2611 AE Delft',
    afstand_km: 19,
    hoofd: 'oprit_terras_terrein',
    sub: ['invegen', 'beschermlaag'],
    m2: 84,
    planten: 'ja',
    planten_afschermen: 'ja',
    groene_aanslag: 'ja',
    korstmos: 'ja',
    voegzand_type: 'onkruidwerend',
    zand_kleur: 'antraciet',
    fotos: 6,
    status: 'info_compleet',
    fase: 'info_verzamelen',
    dashboard_status: 'open',
    totaal_prijs: 736,
    binnengekomen: '4 uur geleden',
    laatste_bericht: 'Ik denk wel ergens 80, 85m². Lastig in te schatten.',
    laatste_richting: 'inkomend',
    wacht_op_klant: false,
    bot_volgende_actie: 'Owner-review nodig: hoge korstmos',
    tag: ['Particulier'],
    binnen_ts: Date.now() - 4 * 3600 * 1000,
    bron: 'formulier',
  },
  {
    id: 'L-2083',
    naam: 'Thomas Wilms',
    bedrijf: null,
    telefoon: '06 - 91 22 87 14',
    email: 'thomas.wilms@gmail.com',
    adres: 'Kanaalstraat 4, 2611 PM Delft',
    afstand_km: 19,
    hoofd: 'oprit_terras_terrein',
    sub: ['invegen'],
    m2: 38,
    planten: 'nee',
    groene_aanslag: 'nee',
    korstmos: 'nee',
    voegzand_type: 'normaal',
    zand_kleur: 'naturel',
    fotos: 2,
    status: 'offerte_verstuurd',
    fase: 'onderhandelen',
    dashboard_status: 'open',
    totaal_prijs: 395,
    binnengekomen: '1 dag geleden',
    laatste_bericht: 'Kan er nog iets van de prijs af? €395 is wat aan de hoge kant.',
    laatste_richting: 'inkomend',
    wacht_op_klant: false,
    bot_volgende_actie: 'Klant vraagt korting — escaleren',
    tag: ['Particulier', '⚠️ Korting'],
    binnen_ts: Date.now() - 86400 * 1000,
    offerte_verstuurd_op: 'gister 11:08',
    bron: 'whatsapp',
  },
  {
    id: 'L-2082',
    naam: 'Sandra Janssen',
    bedrijf: null,
    telefoon: '06 - 35 11 90 02',
    email: 's.janssen@hotmail.com',
    adres: 'Mauritslaan 9, 2628 CD Pijnacker',
    afstand_km: 22,
    hoofd: 'oprit_terras_terrein',
    sub: ['invegen', 'beschermlaag'],
    m2: 156,
    planten: 'ja',
    planten_afschermen: 'nee',
    groene_aanslag: 'ja',
    korstmos: 'nee',
    voegzand_type: 'onkruidwerend',
    zand_kleur: 'antraciet',
    fotos: 5,
    status: 'goedgekeurd',
    fase: 'afspraak_bevestigd',
    dashboard_status: 'open',
    totaal_prijs: 1488,
    binnengekomen: '5 dagen geleden',
    laatste_bericht: 'Geweldig, ik ben thuis vanaf 8u.',
    laatste_richting: 'inkomend',
    wacht_op_klant: false,
    bot_volgende_actie: '—',
    tag: ['Particulier'],
    binnen_ts: Date.now() - 5 * 86400 * 1000,
    afspraak_datum: '2026-05-15',
    afspraak_starttijd: '08:30',
    bron: 'formulier',
  },
  {
    id: 'L-2081',
    naam: 'VVE Stadshof',
    bedrijf: 'VVE Stadshof',
    telefoon: '06 - 24 88 33 99',
    email: 'beheer@vvestadshof.nl',
    adres: 'Hofplein 1-24, 3032 AC Rotterdam',
    afstand_km: 26,
    hoofd: 'onkruidbeheersing_zakelijk',
    sub: ['plan_12_weken'],
    m2: 480,
    planten: 'nee',
    groene_aanslag: 'ja',
    korstmos: 'nee',
    voegzand_type: null,
    fotos: 4,
    status: 'afgewezen',
    fase: 'offerte_besproken',
    dashboard_status: 'geen_interesse',
    totaal_prijs: 1392,
    binnengekomen: '1 week geleden',
    laatste_bericht: 'Bedankt voor de offerte, we gaan voor een ander. Vriendelijke groet.',
    laatste_richting: 'inkomend',
    wacht_op_klant: false,
    bot_volgende_actie: '—',
    tag: ['Zakelijk'],
    binnen_ts: Date.now() - 7 * 86400 * 1000,
    bron: 'formulier',
  },
  {
    id: 'L-2080',
    naam: 'Peter Hofstra',
    bedrijf: null,
    telefoon: '06 - 18 24 50 71',
    email: 'p.hofstra@me.com',
    adres: 'Wilhelminapark 12, 3581 NJ Utrecht',
    afstand_km: 86,
    hoofd: 'oprit_terras_terrein',
    sub: ['invegen', 'beschermlaag'],
    m2: 98,
    planten: 'nee',
    groene_aanslag: 'ja',
    korstmos: 'ja',
    voegzand_type: 'onkruidwerend',
    zand_kleur: 'naturel',
    fotos: 7,
    status: 'wacht_bevestiging',
    fase: 'info_verzamelen',
    dashboard_status: 'open',
    totaal_prijs: 998,
    binnengekomen: '6 uur geleden',
    laatste_bericht: 'Ja klopt, recente foto\'s.',
    laatste_richting: 'inkomend',
    wacht_op_klant: false,
    bot_volgende_actie: 'Buiten radius — owner moet beslissen',
    tag: ['Particulier', '📍 Buiten radius'],
    binnen_ts: Date.now() - 6 * 3600 * 1000,
    bron: 'formulier',
  },
  {
    id: 'L-2079',
    naam: 'Anna Smit',
    bedrijf: null,
    telefoon: '06 - 51 78 22 04',
    email: 'anna.smit@gmail.com',
    adres: 'Beeklaan 67, 2562 AE Den Haag',
    afstand_km: 11,
    hoofd: 'oprit_terras_terrein',
    sub: ['invegen'],
    m2: 45,
    planten: 'nee',
    groene_aanslag: 'nee',
    korstmos: 'nee',
    voegzand_type: 'normaal',
    zand_kleur: 'naturel',
    fotos: 3,
    status: 'goedgekeurd',
    fase: 'afspraak_bevestigd',
    dashboard_status: 'afgehandeld',
    totaal_prijs: 440,
    binnengekomen: '2 weken geleden',
    laatste_bericht: 'Super werk geleverd, helemaal blij mee!',
    laatste_richting: 'inkomend',
    wacht_op_klant: false,
    bot_volgende_actie: '—',
    tag: ['Particulier', '⭐ Review'],
    binnen_ts: Date.now() - 14 * 86400 * 1000,
    afspraak_datum: '2026-05-06',
    bron: 'formulier',
  },
  {
    id: 'L-2078',
    naam: 'David Klein',
    bedrijf: null,
    telefoon: '06 - 28 11 44 73',
    email: 'd.klein@xs4all.nl',
    adres: 'Vondelstraat 91, 2513 EM Den Haag',
    afstand_km: 12,
    hoofd: 'oprit_terras_terrein',
    sub: ['invegen', 'beschermlaag'],
    m2: 72,
    planten: 'ja',
    planten_afschermen: 'ja',
    groene_aanslag: 'ja',
    korstmos: 'nee',
    voegzand_type: 'onkruidwerend',
    zand_kleur: 'antraciet',
    fotos: 4,
    status: 'nieuw',
    fase: 'info_verzamelen',
    dashboard_status: 'open',
    totaal_prijs: null,
    binnengekomen: '2 min geleden',
    laatste_bericht: '(Surface heeft openingsbericht gestuurd)',
    laatste_richting: 'uitgaand',
    wacht_op_klant: true,
    bot_volgende_actie: 'Wacht op eerste antwoord',
    tag: ['Particulier'],
    binnen_ts: Date.now() - 2 * 60 * 1000,
    bron: 'formulier',
  },
];

// WhatsApp conversation for Jeroen de Vries (L-2087) — primary detail
const CONVERSATION_2087 = [
  { day: 'Vandaag' },
  { from: 'bot', time: '09:14', text: 'Hoi Jeroen! 👋 Bedankt voor je aanvraag bij Schoon Straatje. Ik ben Surface, jullie assistent. Ik help je in een paar berichten aan een offerte voor het reinigen + invegen van je oprit. Eerst even checken: klopt het dat het gaat om ongeveer 145m²?' },
  { from: 'customer', time: '09:16', text: 'Ja klopt. Het is de hele oprit + een stukje terras achterin.' },
  { from: 'bot', time: '09:16', text: 'Top, helder. En ik zie dat je hebt aangevinkt dat er groene aanslag zit — voor langer resultaat raad ik een beschermlaag aan (€1,60 per m²). Wil je die meenemen?' },
  { from: 'customer', time: '09:21', text: 'Klinkt goed, ja graag.' },
  { from: 'bot', time: '09:21', text: 'Mooi. Staan er planten of struiken vlak naast de bestrating waar we langs moeten werken?' },
  { from: 'customer', time: '09:28', text: 'Ja, een hortensia en wat lavendel.' },
  { from: 'bot', time: '09:28', text: 'Helder — die schermen we af met folie (€8,50 per rol, schatten 2 rollen). En welke kleur voegzand: naturel of antraciet?' },
  { from: 'customer', time: '09:42', text: 'Antraciet zou mooi staan denk ik.' },
  { from: 'bot', time: '09:42', text: 'Top. Eén ding nog: ik zie dat de foto\'s van eind december zijn — heb je nog recentere? Anders kunnen we doorgaan met deze.' },
  { from: 'customer', time: '10:08', text: 'Hoi! Ja, ongeveer 145m² inderdaad. Foto\'s heb ik net gestuurd.', isPhoto: true },
  { from: 'customer', time: '10:08', isPhoto: true },
  { typing: true },
];

const APPOINTMENTS = [
  { lead: 'L-2085', name: 'Marieke v.d. Heijden', date: '2026-05-19', start: '09:00', end: '12:00', tone: 'blue', adres: 'Rotterdam', m2: 62, dienst: 'Invegen' },
  { lead: 'L-2082', name: 'Sandra Janssen',       date: '2026-05-15', start: '08:30', end: '14:30', tone: 'blue', adres: 'Pijnacker', m2: 156, dienst: 'Invegen + beschermlaag' },
  { lead: 'L-2079', name: 'Anna Smit',            date: '2026-05-13', start: '13:00', end: '15:30', tone: 'green', adres: 'Den Haag', m2: 45, dienst: 'Invegen' },
  { lead: 'L-2081', name: 'VVE Stadshof (intake)', date: '2026-05-14', start: '10:00', end: '11:00', tone: 'amber', adres: 'Rotterdam', m2: 480, dienst: 'Plaatsbezoek' },
];

const KPIS = {
  nieuwe_leads:        { value: 14, delta: '+22%',  trend: [4,7,5,9,12,10,14] },
  conversie:           { value: 64, suffix: '%', delta: '+8 pt', trend: [52,55,58,60,61,62,64] },
  reactietijd:         { value: 47, suffix: 's', delta: '–12s',  trend: [62,58,55,52,50,48,47], invertDelta: true },
  omzet_maand:         { value: 18420, prefix: '€', delta: '+€3.1k', trend: [11000,13000,14500,15800,16400,17800,18420] },
  offertes_open:       { value: 7,  delta: '+2',    trend: [3,4,5,5,6,7,7] },
  afspraken_week:      { value: 4,  delta: '—',     trend: [3,3,4,4,4,4,4] },
};

// Activity feed for overzicht
const ACTIVITY = [
  { kind: 'new',   name: 'Thomas Wilms',  text: 'vroeg om korting op offerte €395',    time: 'net',         leadId: 'L-2083' },
  { kind: 'wa',    name: 'Jeroen de Vries', text: 'stuurde 4 foto\'s — Surface analyseert',  time: '2 min',  leadId: 'L-2087' },
  { kind: 'appt',  name: 'Marieke v.d. Heijden', text: 'bevestigde afspraak voor dinsdag 9:00', time: '24 min', leadId: 'L-2085' },
  { kind: 'quote', name: 'Familie Bakker', text: 'wacht op owner-review (korstmos toeslag)', time: '47 min', leadId: 'L-2084' },
  { kind: 'new',   name: 'David Klein',    text: 'kwam binnen via formulier',           time: '1u 4min',     leadId: 'L-2078' },
  { kind: 'quote', name: 'Bouwbedrijf Korstmos', text: 'offerte €4.180 verstuurd via WhatsApp', time: '2u',  leadId: 'L-2086' },
  { kind: 'appt',  name: 'Sandra Janssen', text: 'afspraak ingepland — vrijdag 8:30',   time: '4u',          leadId: 'L-2082' },
];

// Maand-area-chart datapunten (nieuwe leads per dag, laatste 28 dagen)
const TREND_28D = [
  3, 5, 4, 6, 3, 7, 5,
  6, 8, 4, 9, 7, 11, 6,
  5, 9, 12, 8, 10, 14, 9,
  11, 8, 13, 10, 12, 9, 14,
];

// Door tenant aangeboden diensten met aan/uit
const SERVICE_OFFERINGS = [
  { key: 'oprit_terras_terrein',       label: 'Oprit/terras reiniging + invegen', actief: true },
  { key: 'onkruidbeheersing_zakelijk', label: 'Onkruidbeheersing zakelijk',       actief: false },
];

// Pricing — vanuit config.json
const PRICING_RULES = [
  { key: 'reinigen_per_m2',                  label: 'Reiniging per m²',                      waarde: 3.95, eenheid: '€ / m²' },
  { key: 'reinigen_dagprijs_onder_100m2',    label: 'Reiniging dagprijs (< 100 m²)',         waarde: 395,  eenheid: '€' },
  { key: 'invegen_arbeid_normaal_per_m2',    label: 'Invegen — arbeid normaal',              waarde: 0.90, eenheid: '€ / m²' },
  { key: 'invegen_arbeid_onkruidwerend_per_m2', label: 'Invegen — arbeid onkruidwerend',     waarde: 1.60, eenheid: '€ / m²' },
  { key: 'voegzand_normaal_per_zak',         label: 'Voegzand normaal',                       waarde: 2.90, eenheid: '€ / zak' },
  { key: 'voegzand_onkruidwerend_per_zak',   label: 'Voegzand onkruidwerend',                 waarde: 20.90,eenheid: '€ / zak' },
  { key: 'beschermlaag_per_m2',              label: 'Beschermlaag',                           waarde: 1.60, eenheid: '€ / m²' },
  { key: 'planten_afschermen_folie_per_rol', label: 'Afschermfolie (per rol)',                waarde: 8.50, eenheid: '€ / rol' },
  { key: 'extra_arbeid_per_minuut',          label: 'Extra arbeid',                           waarde: 1.20, eenheid: '€ / min / persoon' },
  { key: 'reiskosten_per_km',                label: 'Reiskosten',                             waarde: 0.23, eenheid: '€ / km' },
  { key: 'reiskosten_gratis_tot_km',         label: 'Reiskosten gratis tot',                  waarde: 50,   eenheid: 'km' },
];

Object.assign(window, {
  FASES,
  STATUS,
  DIENST_LABELS,
  PIPELINE_STAGES,
  LEADS,
  CONVERSATION_2087,
  APPOINTMENTS,
  KPIS,
  ACTIVITY,
  TREND_28D,
  SERVICE_OFFERINGS,
  PRICING_RULES,
});
