do $$ begin create role anon; exception when duplicate_object then null; end $$;
do $$ begin create role authenticated; exception when duplicate_object then null; end $$;
do $$ begin create role service_role; exception when duplicate_object then null; end $$;
create schema if not exists auth;
create or replace function auth.uid() returns uuid language sql stable as $fn$ select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid $fn$;
create schema if not exists storage;
create table if not exists storage.buckets (id text primary key, name text, public boolean default false);
create table if not exists storage.objects (id uuid default gen_random_uuid() primary key, bucket_id text, name text, owner uuid, created_at timestamptz default now());
alter table storage.objects enable row level security;
insert into storage.buckets(id,name,public) values ('klant-fotos','klant-fotos',true) on conflict do nothing;
create or replace function public.trigger_notify_nieuwe_lead() returns trigger language plpgsql as $fn$ begin return new; end $fn$;
create or replace function public.trigger_notify_lead_update() returns trigger language plpgsql as $fn$ begin return new; end $fn$;
create or replace function public.trigger_notification_dispatch() returns trigger language plpgsql as $fn$ begin return new; end $fn$;
create or replace function public.dispatch_notification_delivery(p_id uuid, p_kanaal public.notification_kanaal) returns void language plpgsql as $fn$ begin end $fn$;
create or replace function public.create_notification_for_all_users(p_event_type public.notification_event_type, p_titel text, p_body text, p_lead_id text, p_payload jsonb) returns void language plpgsql as $fn$ begin end $fn$;
create or replace function public.next_offerte_nummer() returns text language sql as $fn$ select '0'::text $fn$;
create or replace function public.is_approved_dashboard_user() returns boolean language sql stable as $fn$ select true $fn$;
insert into public.tenant_settings(id,bedrijfsnaam,chatbot_naam,offerte_nummer_prefix,offerte_nummer_jaar,offerte_nummer_teller) values ('00000000-0000-0000-0000-000000000001','Schoon Straatje','Sara','SS',2026,0);
insert into public.dashboard_user_profiles(user_id,tenant_status,is_owner,bedrijfsnaam) values
 ('1f0901de-dac3-495a-839d-5079086fe5c5','approved',true,'Frontlix'),
 ('7ea749b4-33c9-4c36-a8f7-b1d0595e6843','approved',true,'Schoon Straatje');
insert into public.leads(lead_id,naam) values ('lead-1','Klant 1'),('lead-2','Klant 2');
insert into public.tags(id,naam) values ('11111111-1111-1111-1111-111111111111','Belangrijk');
insert into public.lead_tags(lead_id,tag_id,aangemaakt_door) values ('lead-1','11111111-1111-1111-1111-111111111111','7ea749b4-33c9-4c36-a8f7-b1d0595e6843');
insert into public.offertes(lead_id) values ('lead-1'),('lead-2');
insert into public.berichten(lead_id) values ('lead-1'),('lead-2');
insert into public.fotos(lead_id,storage_path) values ('lead-1','lead-1/foto.jpg');
insert into public.prijsregels(lead_id) values ('lead-1');
insert into public.lead_notes(lead_id,auteur) values ('lead-1','7ea749b4-33c9-4c36-a8f7-b1d0595e6843');
insert into public.lead_status_history(lead_id) values ('lead-1');
insert into public.pending_delivery_checks(lead_id,wa_message_id) values ('lead-1','wamid-1');
insert into public.pricing_rules(rule_key,waarde) values ('reinigen_per_m2',5),('voegzand_per_zak',10);
insert into public.service_offerings(dienst_key,label,actief) values ('reinigen','Reinigen',true);
insert into public.notification_preferences(event_type,kanaal,enabled) values ('nieuwe_lead','in_app',true),('nieuwe_lead','email',true);
insert into public.kostprijzen_per_dienst(rule_key,kost_pct) values ('reinigen',30);
insert into public.offerte_concepten(label) values ('concept-1');
insert into public.template_aanvragen(template_naam,aanvrager_user_id) values ('tmpl-1','7ea749b4-33c9-4c36-a8f7-b1d0595e6843');
insert into public.external_calendar_events(google_event_id,summary) values ('evt-1','Afspraak');
insert into public.notifications(lead_id,user_id) values ('lead-1',null),(null,'7ea749b4-33c9-4c36-a8f7-b1d0595e6843'),(null,null);
insert into public.error_logs(lead_id) values ('lead-1'),(null);
